<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Math_Libirary">
      <HintPath>..\..\MathLibirary\Math_Libirary\bin\Debug\net8.0\Math_Libirary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
